services:
  - type: web  
    plan: free
    name: render.node.js
    runtime: node
    repo: https://github.com/clemzouuu/render
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString

databases:
  - name: database
    plan: free